server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cf6og1l7mjlg.ap-northeast-2.rds.amazonaws.com:3306/bts-project?allowMultiQueries=true
    username: admin
    password: 1q2w3e4r!
  mail:
    host: smtp.gmail.com
    port: 587
    username: yeonho4698@gmail.com
    password: skosucaxgioctlcj
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: khTMhnEExwWfNpdd_Avp
            clientSecret: _jgvXf3H5E
            scope:
              - email
              - name
              - phone
              - nickname
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
          kakao:
            clientId: b83d0f41c645f00cbb4cd4b5224865b8
            clientSecret: FFuEVrMC53mrbRPHoLGwMSjOa0ki0tTj
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/kakao

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id



mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:\project\bts-project-20221102\upload\
